AttractorSchool/ESDP-AP-10-1

- api/serializers.py
- api/urls.py
- api/views/reviews_api_view.py
Через postman с get запросом можно вывести все отзывы и лайки в виде json файла
```
http://127.0.0.1:8000/api/reviews/
```
> Valentin task 40

- api/serializers.py
- static/css/style.css
- webapp/templates/base.html
Создал гамбургер-меню, минимально стилизовал его и исправил наименование полей в модели EventsSerializer в файле 'serializers.py'
> #34 Создание гамбургер-меню

- Dockerfile
- README.md
- app/settings.py
- conf/centrifugo.json
- conf/nginx.conf
- docker-compose.yml
- requirements.txt
Создал файлы, необходимые для работы проекта в докере. Изменил настройки базы данных.
> #52: Перенос проекта на Docker с целью интеграции Centrifugo и Nginx

- api/serializers.py
- api/urls.py
- api/views/profile.py
пользователей через API запрос.
Для проверки критерия приемки, в postman необходимо ввести GET запрос со следующей строкой:
```
http://127.0.0.1:8000/api/accounts/
```
> #57 Реализован функционал вывода списка профилей

- accounts/models/account.py
- accounts/templates/profile_list_view.html
- accounts/urls.py
- accounts/views/profile.py
- api/serializers.py
- app/settings.py
- static/css/style.css
- static/js/profile_list.js
Для проверки критерия успешности, необходимо зайти по ссылке:
```
http://127.0.0.1:8000/auth/profile-list/
```
а также:
```
http://127.0.0.1:8000/api/accounts/
```
> Valentin task 58

- api/serializers.py
- api/urls.py
- api/views/events_api_view.py
- api/views/news_api_view.py
- В файле views.py написал CRUD функций.
- В файле urls.py указал путь при котором будут работать эти функции.
> #62 Написал CRUD операции для новостей через API

- api/serializers.py
- api/urls.py
- api/views/attaching_to_block_api_view.py
- api/views/list_votes.py
- api/views/name_voting_types_api_view.py
- api/views/users_who_voted_api_view.py
- api/views/vote_api_view.py
- api/views/voting_options.py
- api/views/voting_types_api_view.py
Написал сериалайзеры для моделей голосований
В папке views написал crud функции
В urls.py написал пути для вывода этих функций
> #74 Реализовал CRUD операции для моделей голосований через api

- api/views/events_api_view.py
- fixtures/dump_all.json
В папке views, в файле events_api.py исправил ошибку в post запросе
> #80 Исправил ошибку в мероприятии при создании и исправил фикстуры

- accounts/views/authentification.py
- app/settings.py
- requirements.txt
- static/js/check_auth.js
- static/js/login.js
- static/js/logout.js
- static/js/register.js
- templates/base.html
- webapp/views/newsline.py
Добавил приложение django-cors-headers для устранения бага
> #82 Исправить функции регистрации и аутентификации пользователя

- static/css/style.css
- static/js/burger.js
- templates/base.html
- templates/event_detail.html
- templates/newsline.html
- templates/profile_detail.html
Реализовать бургер меню
На всех страницах доступно бургер меню
> #102 Реализовал Бургер-Меню

- static/css/style.css
Изменил стили так, чтобы бургер меню работало корректно
> #124 Исправил Бургер-Меню

- static/css/style.css
- templates/index.html
Реализовал стили индексной страницы в соответствии с утвержденным дизайном
Страница  оформлена в соответствии с дизайном всего приложения
> #141 Создание стилей индексной страницы

- accounts/views/auth.py
- app/settings.py
- conf/centrifugo.json
- conf/nginx.conf
- fixtures/dump_all.json
- static/js/jwt_authorization.js
- static/js/jwt_get_by_email.js
- static/js/jwt_get_by_refresh.js
- static/js/login.js
- static/js/logout.js
- static/js/newsline.js
- static/js/profile_list.js
- static/js/register.js
- static/js/search.js
- Обновил фикстуры
- Добавил IP адрес сервера в конфигурационные файлы centrifugo и nginx
- Добавил IP адрес сервера в разрешенные хосты в settings.py
- Подправил ссылки для совместимости
> #151 Создание переменных окружения для совместимости запуска на сервере и на локальной машине 

- cal/tests.py
- templates/profile_list_django.html
- webapp/tests.py
Написал тесты для календаря и детального просмотра мероприятия. Поместил тесты в файлы tests.py
> #155 Написал тесты для календаря и детального просмотра мероприятия

- cal/urls.py
- cal/utils.py
- cal/views.py
- static/css/style.css
- static/js/calendar_script.js
- templates/base.html
- templates/calendar.html
Произвел анализ текущего бэкенда и JS, затем разработал и реализовал улучшенную версию. Протестировал функционал. Заменил базовую разметку для вывод query параметров
> Переписать бэкенд и JS для календаря task 147

- static/css/style.css
- templates/base.html
- templates/event_detail.html
- templates/newsline.html
- templates/profile_detail.html
- templates/profile_list_django.html
Изменил размеры приложения, теперь при запуске через компьютер запускается в полноэкранном режиме. При запуске через toggle device toolbar на размере Iphone 12 pro все отображается как в мобильном приложении. Не реализованы страницы чата, так как нет к ним доступа из-за ошибки
> #148 Обновленная разметка приложения

- static/css/style.css
- templates/base.html
- templates/event_detail.html
Изменил размеры приложения, теперь при запуске череp разные мобильные устройства высота отображается корректно
> #169 Обновленная разметка приложения

- chat/models.py
- chat/tests.py
- static/css/chat.css
- static/css/style.css
- static/js/login.js
- static/js/register.js
- static/js/room.js
- templates/chat/chat_list.html
- templates/chat/group_detail.html
- templates/chat/room.html
- templates/login.html
- templates/register.html
- Создал тесты для моделей ChatRoom, ChatMessage, ChatRoomMembership, File
- Сделал страницу чата адаптивной
- В детальной странице групчатов: поправил отображение аватарок, увеличил размер шрифта имен и фамилий участников
- Мелкие поправка в стилях чата и чатлиста
- Кнопка "Назад" в чатруме направляет на обновленную страницу чатлиста
- Исправил баг с неполной прокруткой вниз при загрузке картинок
- Добавил кнопку "Зарегистрироваться" на страницу логина, так как была проблема с отображением индексной страницы
- Добавил стилей для сообщений при не/успешном входе/регистрации
> #153 Создание тестов для моделей, связанных с функционалом общения в чате и пересылкой файлов

- accounts/urls.py
- static/css/style.css
- templates/partial/profile_edit_form.html
- templates/profile_detail.html
- templates/profile_edit.html
- webapp/urls.py
- webapp/views/profile.py
Разработал интерфейс для редактирования данных пользователя, включая основные поля профиля.
Функционал редактирования корректно отображает текущие данные пользователя и позволяет их успешно обновлять.
> #159 Осуществление функционала редактирования пользователя

- templates/vote_detail.html
- webapp/views/vote.py
В детальном view голосования добавил context с вычеслением процентов голосования и отобразил на странице голосования
> #183 Доработал голосования, теперь можно видеть резултаты голосования

- .github/workflows/main.yml
> #189 Создал mail.yml с настройками для автоматизации поставки

- static/css/style.css
- templates/profile_edit.html
- templates/request_create.html
- templates/request_list.html
- templates/vote_create.html
- templates/vote_list_create.html
- templates/vote_option_create.html
- webapp/forms.py
Изменить css стили в приложении под мобильную версию. Изменил label для формы поиска. Изменил размеры страницы редактирования пользователя. Изменил страницу создания запроса. Изменил страницу аутентификации. Изменил страницу списка запросов. Изменил страницу создания голосования. И обновил стили для страниц создания голосования
> Замена стилей для страниц под мобильную версию

- templates/request_update.html
- webapp/tests.py
Создал тесты и исправил html страницу обновления данных запроса
> #195 Создал тесты для страниц запросов
